name: Tests

on:
  push:
    branches:
      - main
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        version: [1.5.1]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup merkely CLI
        uses: ./
        with:
          version: ${{ matrix.version }}

      - name: Capture merkely version installed
        run: |
          export MERKELY_VERSION=$( merkely version )
          echo 'MERKELY_VERSION_INSTALLED<<EOF' >> $GITHUB_ENV
          merkely version >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - name: Verify
        shell: python
        env:
          MERKELY_VERSION_EXPECTED: ${{ matrix.version }}
        run: |
          import sys, os
          sys.exit(
              int(not os.environ["MERKELY_VERSION_EXPECTED"] in os.environ["MERKELY_VERSION_INSTALLED"])
          )
